CREATE TABLE "res_users" (
	"id" serial PRIMARY KEY NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"login" varchar,
	"password" varchar,
	"company_id" integer,
	"partner_id" integer,
	"create_date" timestamp,
	"signature" varchar,
	"action_id" integer,
	"share" boolean,
	"create_uid" integer,
	"write_uid" integer,
	"write_date" timestamp,
	"totp_secret" varchar,
	"notification_type" varchar,
	"odoobot_state" varchar,
	"odoobot_failed" boolean,
	"sale_team_id" integer,
	"sidebar_type" varchar,
	"chatter_position" varchar,
	"website_id" integer,
	"karma" integer,
	"rank_id" integer,
	"next_rank_id" integer,
	"provider_id" integer,
	"access_token" varchar
);
