// src/mock/application-form-data.ts
import { AllApplicationFormType } from "@/types/projects";

export const mockApplicationFormData: AllApplicationFormType[] = [
  {
    partner_name: "PT. Teknologi Nusantara",
    office_address: "Jl. Merdeka No. 123, Jakarta",
    invoice_address: "Jl. Cempaka Putih No. 45, Jakarta",
    contact_person: "Budi Santoso",
    phone: "021-12345678",
    departement: "Quality Assurance",
    email: "budi@teknonusantara.co.id",
    website: "teknonusantara.co.id",
    tahapan: "surveilance1",
    standards: ["ISO 9001", "ISO 14001"],
    created_at: "2025-06-01T08:00:00Z",
    updated_at: "2025-06-02T10:00:00Z",
    scope: "Production of electronic components",
    boundaries: "Headquarters only",
    iso_standard: "ISO 9001",
    certificate_type: "Initial Certification",
    audit_stage: "Stage 1",
    number_of_site: 2,
    remarks: "Requires translator for audit",

    type_1: "Manufacturing",
    address_1: "Jl. Industri No. 10, Jakarta",
    activity_1: "Assembly Line A",
    employees_1: 100,

    type_2: "Warehouse",
    address_2: "Jl. Gudang No. 3, Bekasi",
    activity_2: "Storage and Distribution",
    employees_2: 30,

    type_3: "Head Office",
    address_3: "Jl. Merdeka No. 123, Jakarta",
    activity_3: "Management",
    employees_3: 25,
  },
  {
    partner_name: "CV. Solusi Media",
    office_address: "Jl. Soekarno Hatta No. 88, Bandung",
    invoice_address: "Jl. Diponegoro No. 12, Bandung",
    contact_person: "Sari Wulandari",
    phone: "022-9876543",
    departement: "IT Department",
    email: "sari@solusimedia.id",
    website: "solusimedia.id",
    tahapan: "surveilance2",
    standards: ["ISO 27001"],
    created_at: "2025-05-28T09:30:00Z",
    updated_at: "2025-06-01T15:00:00Z",
    scope: "Cloud Service Provision",
    boundaries: "Main Office & Data Center",
    iso_standard: "ISO 27001",
    certificate_type: "Recertification",
    audit_stage: "Stage 2",
    number_of_site: 1,
    remarks: "Need remote access for audit",

    type_1: "IT Operations",
    address_1: "Jl. IT Center No. 11, Bandung",
    activity_1: "Hosting & Maintenance",
    employees_1: 40,
  },
  {
    partner_name: "SD Swasta Bumitama Region Kotawaringin",
    office_address: "Jl. Pendidikan No. 5, Kotawaringin",
    invoice_address: "Jl. Pendidikan No. 5, Kotawaringin",
    contact_person: "Ibu Lina",
    phone: "0531-456789",
    departement: "Administrasi",
    email: "lina@sd-bumitama.sch.id",
    website: "sd-bumitama.sch.id",
    tahapan: "initial",
    standards: ["ISO 21001"],
    created_at: "2025-06-15T08:00:00Z",
    updated_at: "2025-06-16T10:00:00Z",
    scope: "Pendidikan tingkat dasar",
    boundaries: "Seluruh area sekolah",
    iso_standard: "ISO 21001",
    certificate_type: "Initial Certification",
    audit_stage: "Stage 1",
    number_of_site: 1,
    remarks: "-",

    type_1: "Sekolah",
    address_1: "Jl. Pendidikan No. 5, Kotawaringin",
    activity_1: "Kegiatan Belajar Mengajar",
    employees_1: 35,
  },
];
