
import { RegulationType } from "@/types/projects";

export const detailedRegulationData: RegulationType[] = [
  {
    "id": 200,
    "title": "Undang-Undang No 1 Tahun 1970 tentang Keselamatan Kerja",
    "subtitle": "",
    "image": "",
    "number": "1",
    "type": "Undang-Undang",
    "issuer": "Departemen Tenaga Kerdja",
    "sector": "Undang-Undang/PERPUU terkait K3",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "12 Januari 1970",
    "effectiveAt": "12 Januari 1970",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/2/506cd8d4605ab25caf236baccf63d8b0"
  },
  {
    "id": 201,
    "title": "Undang-Undang Uap Tahun 1930 (Stoom Ordonnantie 1930)(Staatsblad No. 225 Tahun 1930)",
    "subtitle": "",
    "image": "",
    "number": "225",
    "type": "Undang-Undang",
    "issuer": "-",
    "sector": "Undang-Undang/PERPUU terkait K3",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "30 Juni 1930",
    "effectiveAt": "30 Juni 1930",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/1/ddf55f1bf1e2edf05232e268211f9bcd"
  },
  {
    "id": 202,
    "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 01/Men/2007 Tentang Pedoman Pemberian Penghargaan K3",
    "subtitle": "",
    "image": "",
    "number": "1",
    "type": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 01/Men/2007",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang SMK3",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "11 Januari 2007",
    "effectiveAt": "11 Januari 2007",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/67/b7181a88f8991742c28bd0441e65ba87"
  },
  {
    "id": 203,
    "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per.26/Men/2014 Tentang Penyelenggaraan Penilaian Penerapan SMK3",
    "subtitle": "",
    "image": "",
    "number": "26",
    "type": "Peraturan Menteri Tenaga Kerja dan Transmigrasi",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang SMK3",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "31 Desember 2014",
    "effectiveAt": "31 Desember 2014",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/38/5b1b0b0386b22878958e8b01aee05330"
  },
  {
    "id": 204,
    "title": "Peraturan Pemerintah Nomor 50 Tahun 2012 tentang Penerapan Sistem Manajemen Keselamatan dan Kesehatan Kerja",
    "subtitle": "",
    "image": "",
    "number": "50",
    "type": "Peraturan Pemerintah",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang SMK3",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "12 April 2012",
    "effectiveAt": "12 April 2012",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/4/6bbb83b41053f6bacd126f8132914083"
  },
  {
    "id": 205,
    "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 04/Men/1987 Tentang Panitia Pembina Keselamatan dan Kesehatan Kerja dan Penunjukan Ahli Kesel",
    "subtitle": "",
    "image": "",
    "number": "4",
    "type": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 04/Men/1987",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Keahlian dan Kelembagaan K3",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "23 Juli 1987",
    "effectiveAt": "23 Juli 1987",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/51/a218806a67e92cee1239202623e22e05"
  },
  {
    "id": 206,
    "title": "Peraturan Menteri Tenaga Kerja Nomor Per-02/MEN/1992 tentang Tata Cara Penunjukan, Kewajiban dan Wewenang Ahli Keselamatan dan Kesehatan Kerja",
    "subtitle": "",
    "image": "",
    "number": "02",
    "type": "Peraturan Menteri",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Keahlian dan Kelembagaan K3",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "30 Desember 1992",
    "effectiveAt": "30 Desember 1992",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/19/bd46f93aa588aeb9983a4aa49ef6c73e"
  },
  {
    "id": 207,
    "title": "Peraturan Menteri Tenaga Kerja Nomor Per-04/MEN/1995 tentang Perusahaan Jasa Keselamatan dan Kesehatan Kerja",
    "subtitle": "",
    "image": "",
    "number": "04",
    "type": "Peraturan Menteri",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Keahlian dan Kelembagaan K3",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "1 Januari 1995",
    "effectiveAt": "1 Januari 1995",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/18/1d4e0815c538eb6b5e1e41f8d2c99f46"
  },
  {
    "id": 208,
    "title": "PERATURAN MENTERI KETENAGAKERJAAN REPUBLIK INDONESIA NOMOR 4 TAHUN 2025 TENTANG OPERATOR PESAWAT UAP",
    "subtitle": "",
    "image": "",
    "number": "NOMOR 4 TAHUN 2025",
    "type": "PERATURAN MENTERI KETENAGAKERJAAN REPUBLIK INDONESIA NOMOR 4 TAHUN 2025",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Uap",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "22 Mei 2025",
    "effectiveAt": "22 Mei 2025",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/99/83133d6241cdc033c2e205b405e849e2"
  },
  {
    "id": 209,
    "title": "Checklist Pemeriksaan Pesawat Uap",
    "subtitle": "",
    "image": "",
    "number": "-",
    "type": "Bentuk",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Uap",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "3 Januari 2022",
    "effectiveAt": "3 Januari 2022",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/83/91f9aae9984ccd018d45a511fdea1f2d"
  },
  {
    "id": 210,
    "title": "Bentuk 9A Pemeriksaan Pertama Pesawat Uap selain Ketel Uap",
    "subtitle": "",
    "image": "",
    "number": "9A",
    "type": "Bentuk",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Uap",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "3 Januari 2022",
    "effectiveAt": "3 Januari 2022",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/82/72140e7301cb5e7e35b4b6fb54bc19b5"
  },
  {
    "id": 211,
    "title": "Bentuk 9 Pemeriksaan Pertama Ketel Uap",
    "subtitle": "",
    "image": "",
    "number": "9",
    "type": "Bentuk",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Uap",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "3 Januari 2022",
    "effectiveAt": "3 Januari 2022",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/81/0062dd7644dbe644d6f44b7d6360cfba"
  },
  {
    "id": 212,
    "title": "Bentuk 10 Laporan Bulanan Pemeriksaan Pesawat Uap dan Bejana Tekanan",
    "subtitle": "",
    "image": "",
    "number": "10",
    "type": "Bentuk",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Uap",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "3 Januari 2022",
    "effectiveAt": "3 Januari 2022",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/80/1ae8c911c20dd4a0699d33e64061d3bb"
  },
  {
    "id": 213,
    "title": "Bentuk U-5 Laporan Pengawasan Pembuatan Pesawat Uap",
    "subtitle": "",
    "image": "",
    "number": "U-5",
    "type": "Bentuk",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Uap",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "3 Januari 2022",
    "effectiveAt": "3 Januari 2022",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/79/b82afc953f86f040f6dff6afad9e2acc"
  },
  {
    "id": 214,
    "title": "Bentuk 1 Akte Izin Penggunaan Pesawat Uap",
    "subtitle": "",
    "image": "",
    "number": "1",
    "type": "Bentuk",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Uap",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "3 Januari 2022",
    "effectiveAt": "3 Januari 2022",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/78/21d8170cf4a72df310f68d73c4061f45"
  },
  {
    "id": 215,
    "title": "Bentuk 6B Surat Permohonan Surat Keterangan Kelayakan Pesawat Uap",
    "subtitle": "",
    "image": "",
    "number": "6B",
    "type": "Bentuk",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Uap",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "3 Januari 2022",
    "effectiveAt": "3 Januari 2022",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/77/e693a0fb8372947b2cd3cc861d42adde"
  },
  {
    "id": 216,
    "title": "Bentuk 6A Surat Permohonan Pengesahan Gambar Rencana Pesawat Uap",
    "subtitle": "",
    "image": "",
    "number": "6A",
    "type": "Bentuk",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Uap",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "3 Januari 2022",
    "effectiveAt": "3 Januari 2022",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/76/a8ea90750f46173fe155108454df2911"
  },
  {
    "id": 217,
    "title": "Bentuk 6 Surat Permohonan Penggunaan Pesawat Uap",
    "subtitle": "",
    "image": "",
    "number": "6",
    "type": "Bentuk",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Uap",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "3 Januari 2022",
    "effectiveAt": "3 Januari 2022",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/75/42f22a2494367e839c71d89cbb07a992"
  },
  {
    "id": 218,
    "title": "Peraturan Uap Tahun 1930 (Stoom Verordening)",
    "subtitle": "",
    "image": "",
    "number": "-",
    "type": "Peraturan Uap Tahun 1930 (Stoom Verordening)",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Uap",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "2 Februari 1930",
    "effectiveAt": "2 Maret 1930",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/40/dafc7afc2d709e4de7bf56b503323ec3"
  },
  {
    "id": 219,
    "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per.01/Men/1988 Tentang Kwalifikasi dan Syarat-Syarat Operator Pesawat Uap",
    "subtitle": "",
    "image": "",
    "number": "1",
    "type": "Peraturan Menteri Tenaga Kerja dan Transmigrasi",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Uap",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "25 Januari 1988",
    "effectiveAt": "25 Januari 1988",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/39/ab8fc905984358a4ee1fb74be373514a"
  },
  {
    "id": 220,
    "title": "Peraturan Menteri Tenaga Kerja Nomor Per-01/MEN/1992 tentang Syarat-Syarat Keselamatan dan Kesehatan Kerja Pesawat Karbid",
    "subtitle": "",
    "image": "",
    "number": "01",
    "type": "Peraturan Menteri",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Bejana Tekanan dan Tangki Timbun",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "5 Mei 1992",
    "effectiveAt": "5 Mei 1992",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/20/dbc6190b4f58b7ef096c01a0b695a480"
  },
  {
    "id": 221,
    "title": "Peraturan Menteri Ketenagakerjaan RI Nomor 37 Tahun 2016 tentang Keselamatan dan Kesehatan Kerja Bejana Tekanan dan Tangki Timbun",
    "subtitle": "",
    "image": "",
    "number": "37",
    "type": "Peraturan Menteri",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Bejana Tekanan dan Tangki Timbun",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "27 Desember 2016",
    "effectiveAt": "27 Desember 2016",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/5/62e5d2b779e51361bec18520e075af19"
  },
  {
    "id": 222,
    "title": "Lampiran Peraturan Menteri Ketenagakerjaan Tentang Keselamatan dan Kesehatan Kerja No. 8 Tahun 2020 Tentang  Pesawat Angkat dan Pesawat Angkut",
    "subtitle": "",
    "image": "",
    "number": "8",
    "type": "Lampiran Peraturan Menteri Ketenagakerjaan",
    "issuer": "-",
    "sector": "Norma, Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Pesawat Angkat dan Pesawat Angkut",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "6 Agustus 2020",
    "effectiveAt": "6 Desember 2020",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/37/8e11b4f66f38ad0ba03459fe28fccc73"
  },
  {
    "id": 223,
    "title": "Peraturan Menteri Ketenagakerjaan No. 8 Tahun 2020 Tentang Keselamatan dan Kesehatan Kerja Pesawat Angkat dan Pesawat Angkut",
    "subtitle": "",
    "image": "",
    "number": "8",
    "type": "Peraturan Menteri Ketenagekerjaan",
    "issuer": "-",
    "sector": "Norma, Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Pesawat Angkat dan Pesawat Angkut",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "8 Juni 2020",
    "effectiveAt": "12 Juni 2020",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/36/507d2713af278c4e2c45df19ad98637b"
  },
  {
    "id": 224,
    "title": "Peraturan Menteri Ketenagakerjaan RI Nomor 38 Tahun 2016 tentang Keselamatan dan Kesehatan Kerja Pesawat Tenaga dan Produksi",
    "subtitle": "",
    "image": "",
    "number": "38",
    "type": "Peraturan Menteri",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Pesawat Tenaga dan Produksi",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "27 Desember 2016",
    "effectiveAt": "27 Desember 2016",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/6/e79f0bf3ed54c46e5114a00128b409d9"
  },
  {
    "id": 225,
    "title": "Sertifikasi Kompetensi K3 Bidang Konstruksi Bangunan",
    "subtitle": "",
    "image": "",
    "number": "20",
    "type": "Keputusan Dirjen Binwasnaker",
    "issuer": "",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Konstruksi dan Bangunan",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "30 Juni 2004",
    "effectiveAt": "30 Juni 2004",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/74/907e0c41cc48103218c8d56d86f9249a"
  },
  {
    "id": 226,
    "title": "Kepdirjen Binwasnaker No. 74/PPK/XII/2013 Tentang Lisensi K3 Bidang Supervisi Perancah",
    "subtitle": "",
    "image": "",
    "number": "74",
    "type": "Kepdirjen Binwasnaker No. 74/PPK/XII/2013 Tentang Lisensi K3 Bidang Supervisi Pe",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Konstruksi dan Bangunan",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "31 Desember 2013",
    "effectiveAt": "31 Desember 2013",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/45/0da51aa96944437f6907cf91a653e32e"
  },
  {
    "id": 227,
    "title": "Keputusan Dirjen PHI dan Wasnaker No. 20/DJPPK/VI/2004 Tentang Sertifikasi Kompetensi K3 Bidang Konstruksi Bangunan",
    "subtitle": "",
    "image": "",
    "number": "20",
    "type": "Keputusan Dirjen PHI dan Wasnaker No. 20/DJPPK/VI/2004 Tentang Sertifikasi Kompe",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Konstruksi dan Bangunan",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "30 Juni 2004",
    "effectiveAt": "30 Juni 2004",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/44/744c600a24c231c8de880fb6c0a96302"
  },
  {
    "id": 228,
    "title": "Surat Edaran No. S. 4 Tahun 1997 Dirjen PHI dan Wasnaker Tentang Wajib Lapor Pekerjaan Proyek Konstruksi Bangunan",
    "subtitle": "",
    "image": "",
    "number": "4",
    "type": "Surat Edaran No. S. 4 Tahun 1997 Dirjen PHI dan Wasnaker",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Konstruksi dan Bangunan",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "4 Maret 1997",
    "effectiveAt": "4 Maret 1997",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/43/0ac24dbebdadced505bb4e884027f23a"
  },
  {
    "id": 229,
    "title": "Keputusan Bersama Menteri Tenaga Kerja dan Menteri Pekerjaan Umum No. 174/Men/1986 tentang Keselamatan dan Kesehatan Kerja Pada Tempat Kegiatan Konstr",
    "subtitle": "",
    "image": "",
    "number": "174",
    "type": "Keputusan Bersama Menteri Tenaga Kerja dan Menteri Pekerjaan Umum",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Konstruksi dan Bangunan",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "4 Maret 1986",
    "effectiveAt": "4 April 1986",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/42/01fe602f742454e5ed5b871064a18f29"
  },
  {
    "id": 230,
    "title": "Peraturan Menteri Tenaga Kerja No. Per.01/Men/1980 Tentang Keselamatan dan Kesehatan Kerja Pada Konstruksi Bangunan",
    "subtitle": "",
    "image": "",
    "number": "1",
    "type": "Peraturan Menteri Tenaga Kerja",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Konstruksi dan Bangunan",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "6 Maret 1980",
    "effectiveAt": "6 Maret 1980",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/41/99ba911ce716a9fa834293f9ffb65a6e"
  },
  {
    "id": 231,
    "title": "Kepdirjen Binwasnaker dan K3 No.Kep. 48/PPK&K3/VIII/2015 Tentang Pembinaan Teknii K3 Listrik",
    "subtitle": "",
    "image": "",
    "number": "48",
    "type": "Kepdirjen Binwasnaker dan K3 No.Kep. 48/PPK&K3/VIII/2015",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Listrik dan Penyalur Petir",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "5 Agustus 2015",
    "effectiveAt": "5 Agustus 2015",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/56/693f3f7b79526b1d84d9908ada41d028"
  },
  {
    "id": 232,
    "title": "Kepdirjen Binwasnaker dan K3 No.Kep. 47/PPK&K3/VIII/2015 Tentang Pembinaan Calon Ahli K3 Bidang Listrik",
    "subtitle": "",
    "image": "",
    "number": "47",
    "type": "Kepdirjen Binwasnaker dan K3 No.Kep. 47/PPK&K3/VIII/2015",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Listrik dan Penyalur Petir",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "5 Agustus 2015",
    "effectiveAt": "5 Agustus 2015",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/55/6e474e30bad2d3f7aebf66e59cf5ba07"
  },
  {
    "id": 233,
    "title": "Peraturan Menteri Tenaga Kerja No. Per. 02/Men/1989 Tentang Pengawasan Instalasi Penyalur Petir",
    "subtitle": "",
    "image": "",
    "number": "02",
    "type": "Peraturan Menteri Tenaga Kerja No. Per. 02/Men/1989 Tentang Pengawasan Instalasi",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Listrik dan Penyalur Petir",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "21 Februari 1989",
    "effectiveAt": "21 Februari 1989",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/46/b47214a59062b6a0affa8167e19245e2"
  },
  {
    "id": 234,
    "title": "Peraturan Menteri Ketenagakerjaan RI Nomor 12 Tahun 2015 tentang Keselamatan dan Kesehatan Kerja Listrik di Tempat Kerja",
    "subtitle": "",
    "image": "",
    "number": "12",
    "type": "Peraturan Menteri",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Listrik dan Penyalur Petir",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "9 April 2015",
    "effectiveAt": "16 April 2015",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/17/20d1196b5d1138a8d00c388620502001"
  },
  {
    "id": 235,
    "title": "Peraturan Menteri Ketenagakerjaan RI Nomor 33 Tahun 2015 tentang Perubahan Atas Peraturan Menteri Ketenagakerjaan Nomor 12 Tahun 2015 tentang Keselama",
    "subtitle": "",
    "image": "",
    "number": "33",
    "type": "Peraturan Menteri",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Listrik dan Penyalur Petir",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "16 Oktober 2015",
    "effectiveAt": "20 Oktober 2015",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/16/47e45de6f37487f8d4ff4aea06546112"
  },
  {
    "id": 236,
    "title": "Peraturan Menteri Ketenagakerjaan RI Nomor 31 Tahun 2015 tentang Perubahan Atas Peraturan Menteri Tenaga Kerja Nomor Per.02/MEN/1989 tentang Pengawasa",
    "subtitle": "",
    "image": "",
    "number": "31",
    "type": "Peraturan Menteri",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Listrik dan Penyalur Petir",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "16 Oktober 2015",
    "effectiveAt": "20 Oktober 2015",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/15/89e5a739621e47d2381ad0dd26c68c13"
  },
  {
    "id": 237,
    "title": "Peraturan Menteri Ketenagakerjaan RI Nomor 6 Tahun 2017 tentang Keselamatan dan Kesehatan Kerja Elevator dan Eskalator",
    "subtitle": "",
    "image": "",
    "number": "6",
    "type": "Peraturan Menteri",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Elevator dan Eskalator",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "6 Juli 2017",
    "effectiveAt": "6 Juli 2017",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/7/e818d137a7b9961e8fe3c316818048b9"
  },
  {
    "id": 238,
    "title": "PEDOMAN PEMBERIAN PENGHARGAAN PROGRAM PENCEGAHAN DAN PENANGGULANGAN HIV DAN AIDS DI TEMPAT KERJA",
    "subtitle": "",
    "image": "",
    "number": "KEP. 44/PPK /VIII/2012",
    "type": "Keputusan Dirjen",
    "issuer": "--",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "14 Agustus 2012",
    "effectiveAt": "14 Agustus 2012",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/72/e8802dc6cd577dd5fac2d24bff1f34ad"
  },
  {
    "id": 239,
    "title": "Surat Edaran Menteri Tenaga dan Transmigrasi No.SE.01/MEN/1979 Tentang PENGADAAN KANTIN DAN RUANG TEMPAT MAKAN",
    "subtitle": "",
    "image": "",
    "number": "01",
    "type": "Surat Edaran Menteri Tenaga dan Transmigrasi No.SE.01/MEN/1979",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "28 Februari 1979",
    "effectiveAt": "28 Februari 1979",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/68/d13f2221580d4d7e0ba55789f291347c"
  },
  {
    "id": 240,
    "title": "Keputusan Menteri Tenaga Kerja dan Transmigrasi No. Kep. 68/Men/IV/2004 Tentang Pencegahan dan Penanggulangan HIV/AIDS di Tempat Kerja",
    "subtitle": "",
    "image": "",
    "number": "68",
    "type": "Keputusan Menteri Tenaga Kerja dan Transmigrasi No. Kep. 68/Men/IV/2004",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "25 Februari 2004",
    "effectiveAt": "25 Februari 2004",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/66/df509ff9d894223ac165ec8516f5142a"
  },
  {
    "id": 241,
    "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 11/Men/VI/2005 Tentang Pencegahan dan Penanggulangan Penyalahgunaan dan Peredaran Narkotika,",
    "subtitle": "",
    "image": "",
    "number": "11",
    "type": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 11/Men/VI/2005",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "27 Mei 2005",
    "effectiveAt": "27 Mei 2005",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/65/b545f427c285a5d1116bdf76d736980f"
  },
  {
    "id": 242,
    "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 01/Men/1981 Tentang Kewajiban Melapor Penyakit Akibat Kerja",
    "subtitle": "",
    "image": "",
    "number": "01",
    "type": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 01/Men/1981",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "4 April 1981",
    "effectiveAt": "4 April 1981",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/64/4315fc478b85a4cbb8469201699cc03b"
  },
  {
    "id": 243,
    "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 15/Men/VIII/2008 Tentang P3K di Tempat Kerja",
    "subtitle": "",
    "image": "",
    "number": "15",
    "type": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 15/Men/VIII/2008",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "13 Agustus 2008",
    "effectiveAt": "13 Agustus 2008",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/63/8ff5c0b1594572e99d2c6af63bea1630"
  },
  {
    "id": 244,
    "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 03/Men/1982 Tentang Pelayanan Kesehatan Tenaga Kerja",
    "subtitle": "",
    "image": "",
    "number": "03",
    "type": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 03/Men/1982",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "23 April 1982",
    "effectiveAt": "23 April 1982",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/62/a9151f0bd3dd2411894e6d0bb567b6e3"
  },
  {
    "id": 245,
    "title": "Peraturan Menteri Tenaga Kerja, Transmigrasi, dan Koperasi No. Per. 01/Men/1976 Tentang Kewajiban Latihan Hyperkes Dokter Perusahaan",
    "subtitle": "",
    "image": "",
    "number": "01",
    "type": "Peraturan Menteri Tenaga Kerja, Transmigrasi, dan Koperasi No. Per. 01/Men/1976",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "13 Juni 1976",
    "effectiveAt": "13 Juni 1976",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/61/0d66061cd4bada88169540a250578799"
  },
  {
    "id": 246,
    "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 02/Men/1980 Tentang Pemeriksaan Kesehatan Tenaga Kerja dalam Rangka Penyelenggaraan Keselamat",
    "subtitle": "",
    "image": "",
    "number": "02",
    "type": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 02/Men/1980",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "9 Juni 1980",
    "effectiveAt": "9 Juni 1980",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/60/e5877dd2eb4ed8b16d77e6d13951d760"
  },
  {
    "id": 247,
    "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 01/Men/1979 Tentang Kewajiban Latihan Hygiene Perusahaan K3 Bagi Tenaga Medis Perusahaan",
    "subtitle": "",
    "image": "",
    "number": "01",
    "type": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 01/Men/1979",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "28 Februari 1979",
    "effectiveAt": "28 Februari 1979",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/59/6d109c0395c151851e54227230b87d89"
  },
  {
    "id": 248,
    "title": "PEDOMAN PEMBERIAN PENGHARGAAN PROGRAM PENCEGAHAN DAN PENANGGULANGAN COVID-19 DI TEMPAT KERJA",
    "subtitle": "",
    "image": "",
    "number": "5/20/AS.02.02/III/2021",
    "type": "KEPUTUSAN DIREKTUR JENDERAL",
    "issuer": "0",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "9 Maret 2021",
    "effectiveAt": "9 Maret 2021",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/33/18723e1045cdcea6ec0f1d09898afd7f"
  },
  {
    "id": 249,
    "title": "ANTISIPASI MENINGKATNYA KASUS KONFIRMASI COVID 19 DI TEMPAT KERJA",
    "subtitle": "",
    "image": "",
    "number": "5/334/AS.02.02/IX/2020",
    "type": "SE DIRJEN Binwasnaker",
    "issuer": "--",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "28 September 2020",
    "effectiveAt": "28 September 2020",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/32/c2e7e490c1a9652f48e4a6726d5e6a11"
  },
  {
    "id": 250,
    "title": "Senam Pekerja Sehat",
    "subtitle": "",
    "image": "",
    "number": "317",
    "type": "Peraturan Menteri",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "7 Desember 2020",
    "effectiveAt": "7 Desember 2020",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/31/9dc83b06ff5427b33023fc24b6ee0541"
  },
  {
    "id": 251,
    "title": "Pedoman Penyusunan Keberlangsungan Usaha Dalam Masa Pandemi Penyakit",
    "subtitle": "",
    "image": "",
    "number": "312",
    "type": "Peraturan Menteri",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "7 Desember 2020",
    "effectiveAt": "7 Desember 2020",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/30/6d4dde885f2bf7a259dd410825604be0"
  },
  {
    "id": 252,
    "title": "Kewaspadaan Penyebaran Penyakit Pneumonia Berat yang Tidak Diketahui Penyebabnya pada Pekerja",
    "subtitle": "",
    "image": "",
    "number": "B.5/51/AS.02.02/I/2020",
    "type": "Surat Direktur Jenderal Pembinaan Pengawasan Ketenagakerjaan dan K3",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "24 Januari 2020",
    "effectiveAt": "24 Januari 2020",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/26/e4f955fba84edd6e02f1a9860996b890"
  },
  {
    "id": 253,
    "title": "Kesiapsiagaan dalam Menghadapi Penyebaran Covid-19 di Tempat Kerja",
    "subtitle": "",
    "image": "",
    "number": "5/193/AS.02.02/III/2020",
    "type": "Surat Direktur Jenderal Pembinaan Pengawasan Ketenagakerjaan dan K3",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "12 Maret 2020",
    "effectiveAt": "12 Maret 2020",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/25/ca247643b93d7eafa74665c228fa04c7"
  },
  {
    "id": 254,
    "title": "Perlindungan Pekerja/Buruh dalam Program Jaminan Kecelakaan Kerja pada Kasus Penyakit Akibat Kerja karena Corona Virus Disease (COVID-19)",
    "subtitle": "",
    "image": "",
    "number": "M/8/HK.04/V/2020",
    "type": "Surat Edaran Menteri Ketenagakerjaan RI",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "28 Mei 2020",
    "effectiveAt": "28 Mei 2020",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/24/db3609870caec32a98edf5df8ffefe02"
  },
  {
    "id": 255,
    "title": "Perlindungan Pekerja/Buruh dan Kelansungan Usaha dalam Rangka Pencegahan dan Penanggulangan COVID-19",
    "subtitle": "",
    "image": "",
    "number": "M/3/HK.04/III/2020",
    "type": "Surat Edaran Menteri Ketenagakerjaan RI",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "17 Maret 2020",
    "effectiveAt": "17 Maret 2020",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/23/94f7972e1a54fa62de7511954b8166cd"
  },
  {
    "id": 256,
    "title": "Protokol Keselamatan Dan Kesehatan Kerja (K3)  Kembali Bekerja Dalam Pencegahan Penularan Covid-19",
    "subtitle": "",
    "image": "",
    "number": "5/76/HM.01/VII/2020",
    "type": "Keputusan Dirjen",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "22 Juli 2020",
    "effectiveAt": "22 Juli 2020",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/22/4f1a2927dd64483c6d9de5ed311da492"
  },
  {
    "id": 257,
    "title": "Pedoman Penyusunan Perencanaan Keberlangsungan Usaha Dalam Menghadapi Pandemi Corona Virus Disease 2019 (Covid-19) Bagi Usaha Kecil Dan Menengah (UKM)",
    "subtitle": "",
    "image": "",
    "number": "5/77/HM.01/VII/2020",
    "type": "Keputusan Dirjen",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "22 Juli 2020",
    "effectiveAt": "22 Juli 2020",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/21/25e49b4dff0822e805edfdd1313a099c"
  },
  {
    "id": 258,
    "title": "Surat Edaran Direktur Jenderal Binwasnaker dan K3 Nomor 5/1923/AS.02.03/VI/2020 tentang Pembinaan K3 dalam masa Pandemi Covid-19",
    "subtitle": "",
    "image": "",
    "number": "5/1923/AS.02.03/VI/2020",
    "type": "Surat Edaran Direktur Jenderal",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "16 Juni 2020",
    "effectiveAt": "16 Juni 2020",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/11/cad0ca05752d8f1b2a5401c0c34d839d"
  },
  {
    "id": 259,
    "title": "Keputusan Direktur Jenderal Pembinaan Pengawasan Ketenagakerjaan dan Keselamatan dan Kesehatan Kerja Nomor 5/36/HM.01/IV/2020 tentang Pedoman Penyusun",
    "subtitle": "",
    "image": "",
    "number": "5/36/HM.01/IV/2020",
    "type": "Keputusan Dirjen",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "29 April 2020",
    "effectiveAt": "29 April 2020",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/10/65b241773778c16a953e5814df578a3c"
  },
  {
    "id": 260,
    "title": "Surat Edaran Menteri Ketenagakerjaan RI Nomor M/7/AS.02.02/V/2020 tentang Rencana Keberlangsungan Usaha dalam Menghadapi Pandemi Corona Virus Disease",
    "subtitle": "",
    "image": "",
    "number": "M/7/AS.02.02/V/2020",
    "type": "Surat Edaran Menteri Ketenagakerjaan",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "20 Mei 2020",
    "effectiveAt": "20 Mei 2020",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/9/89877beaef49b83d4129a3249bfefc04"
  },
  {
    "id": 261,
    "title": "Surat Edaran Menteri Tenaga dan Transmigrasi No.SE.01/MEN/PPK/IV/2012Tentang Kewajiban Syarat-Syarat Keselamatan dan Kesehatan Kerja di Ruang Terbatas",
    "subtitle": "",
    "image": "",
    "number": "1",
    "type": "Surat Edaran Menteri Tenaga dan Transmigrasi No.SE.01/MEN/PPK/IV/2012",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Ergonomi dan Lingkungan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "9 April 2012",
    "effectiveAt": "9 April 2012",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/48/147ff27513a1dbeaebc915860f43e5f4"
  },
  {
    "id": 262,
    "title": "Peraturan Menteri Ketenagakerjaan No. 9 Tahun 2016 Tentang Keselamatan dan Kesehatan Kerja Pada Ketinggian",
    "subtitle": "",
    "image": "",
    "number": "9",
    "type": "Peraturan Menteri Ketenagakerjaan No. 9 Tahun 2016",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Ergonomi dan Lingkungan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "10 Maret 2016",
    "effectiveAt": "10 Maret 2016",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/47/a533cdb952f0b94b1428ccb0bfc81754"
  },
  {
    "id": 263,
    "title": "Peraturan Menteri Ketenagakerjaan RI Nomor 5 Tahun 2018 tentang Keselamatan dan Kesehatan Kerja Lingkungan Kerja",
    "subtitle": "",
    "image": "",
    "number": "5",
    "type": "Peraturan Menteri",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Ergonomi dan Lingkungan Kerja",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "27 April 2018",
    "effectiveAt": "27 April 2018",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/8/01be2bc7a2c52ffe68b7b885e4761972"
  },
  {
    "id": 264,
    "title": "Keputusan Menteri Tenaga Kerja No. Kep.187/Men/1999 Tentang Pengendalian Bahan Berbahaya di Tempat Kerja",
    "subtitle": "",
    "image": "",
    "number": "187",
    "type": "Keputusan Menteri Tenaga Kerja No. Kep.187/Men/1999",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Bahan Berbahaya",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "29 September 1999",
    "effectiveAt": "29 September 1999",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/49/39b116e7c52134de3f6a66d0a259924d"
  },
  {
    "id": 265,
    "title": "Tata Cara Pembinaan Personel K3 di PJK3 dan PNBP V.3.2.",
    "subtitle": "",
    "image": "",
    "number": "Versi 3.2.",
    "type": "User Guide",
    "issuer": "-",
    "sector": "User Guide",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "1 Juli 2024",
    "effectiveAt": "31 Agustus 2024",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/96/99596699cac2517e8ff43eb982938927"
  },
  {
    "id": 266,
    "title": "Tata Cara Pengajuan SKP PJK3  V.3.0",
    "subtitle": "",
    "image": "",
    "number": "Versi 3.0",
    "type": "User Guide",
    "issuer": "-",
    "sector": "User Guide",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "1 Februari 2024",
    "effectiveAt": "1 Februari 2024",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/95/a8e89a6225b656bde86403e5b4ec4917"
  },
  {
    "id": 267,
    "title": "Tata Cara Pendaftaran SKP Dokter Perusahaan",
    "subtitle": "",
    "image": "",
    "number": "SKP Dokter Ver.1.0",
    "type": "User Guide",
    "issuer": "-",
    "sector": "User Guide",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "1 Agustus 2023",
    "effectiveAt": "1 Agustus 2023",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/92/12fca7bdcae3d9ae0b5982cb1ff77d94"
  },
  {
    "id": 268,
    "title": "Tata Cara PENDAFTARAN SKP AHLI - AUDITOR INTERNAL",
    "subtitle": "",
    "image": "",
    "number": "Personel SKP Ver.1.0",
    "type": "User Guide",
    "issuer": "-",
    "sector": "User Guide",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "1 Oktober 2022",
    "effectiveAt": "1 Oktober 2022",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/87/9acb3bf5ee001ad2e8b6d719798eeec4"
  },
  {
    "id": 269,
    "title": "Tata Cara Perpanjangan Personel V 2.1",
    "subtitle": "",
    "image": "",
    "number": "Personel ver 2.1",
    "type": "User Guide",
    "issuer": "-",
    "sector": "User Guide",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "20 Juli 2022",
    "effectiveAt": "20 Juli 2022",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/85/22abeaca7676f3ae0b3860ee54c8fd2d"
  },
  {
    "id": 270,
    "title": "Tata Cara Teman K3 bagi PJK3 ver 2.1",
    "subtitle": "",
    "image": "",
    "number": "PJK3 ver 2.1",
    "type": "User Guide",
    "issuer": "-",
    "sector": "User Guide",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "4 Juli 2022",
    "effectiveAt": "4 Juli 2022",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/13/05fd565437ffd57c5bdb123033c208c6"
  },
  {
    "id": 271,
    "title": "Surat Edaran Direktur BKK3 Nomor 5/244/AS.02/VIII/2021 tentang Pelaksanaan Pembinaan K3 Wilayah yang Menerapkan PPKM Level 4, Level 3, Level 2",
    "subtitle": "",
    "image": "",
    "number": "5/244/AS.02/VIII/2021",
    "type": "Surat Edaran",
    "issuer": "-",
    "sector": "Surat Edaran",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "5 Agustus 2021",
    "effectiveAt": "5 Agustus 2021",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/71/bb859aeae08231538faa6c44ab687209"
  },
  {
    "id": 272,
    "title": "Optimalisasi Penerapan Protokol Kesehatan di Tempat Kerja dan Penyedian Perlengkapan Serta Sarana Kesehatan Bagi Pekerja/Buruh Oleh Perusahaan Selama",
    "subtitle": "",
    "image": "",
    "number": "M/9/HK.O4/VII/2021",
    "type": "Surat Edaran Menteri",
    "issuer": "--",
    "sector": "Surat Edaran",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "3 Juli 2021",
    "effectiveAt": "3 Juli 2021",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/70/660628eb4d5d168787539d86b91d173a"
  },
  {
    "id": 273,
    "title": "Surat Edaran Direktur BKK3 Nomor 5/181/AS.02.00/VII/2021 tentang Pelaksanaan Pembinaan K3 Wilayah yang Menerapkan PPKM Darurat",
    "subtitle": "",
    "image": "",
    "number": "5/181/AS.02.00/VII/2021",
    "type": "SE Direktur Bina Kelembagaan K3",
    "issuer": "-",
    "sector": "Surat Edaran",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "12 Juli 2021",
    "effectiveAt": "12 Juli 2021",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/35/9fcdd338e2362d4a545a841a1950bf2a"
  },
  {
    "id": 274,
    "title": "Surat Edaran Direktur BKK3 Nomor 5/170/AS.02.00/VII/2021 tentang Pembinaan K3 pada Masa PPKM Darurat Jawa Bali Juli 2021",
    "subtitle": "",
    "image": "",
    "number": "5/170/AS.02.00/VII/2021",
    "type": "SE Direktur Bina Kelembagaan K3",
    "issuer": "-",
    "sector": "Surat Edaran",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "5 Juli 2021",
    "effectiveAt": "5 Juli 2021",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/34/06104a37df799e37fc95229255de58b4"
  },
  {
    "id": 275,
    "title": "Surat Edaran Direktur Pengawasan Norma K3 Nomor 5/2419/AS.02.00/VIII/2020 tentang Pelaksanaan Pembinaan K3",
    "subtitle": "",
    "image": "",
    "number": "5/2419/AS.02.00/VIII/2020",
    "type": "Surat Edaran",
    "issuer": "-",
    "sector": "Surat Edaran",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "5 Agustus 2020",
    "effectiveAt": "5 Agustus 2020",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/14/1a677be31836a755a1fea7c208ef376f"
  },
  {
    "id": 276,
    "title": "Surat Edaran Direktur Pengawasan Norma K3 Nomor 5/1007/AS.02/IV/2020 tentang Pembinaan K3 Berbasis Dalam Jaringan (Online)",
    "subtitle": "",
    "image": "",
    "number": "5/1007/AS.02/IV/2020",
    "type": "Surat Edaran Direktur Pengawasan Norma K3",
    "issuer": "Direktorat Pengawasan Norma K3",
    "sector": "Surat Edaran",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "15 April 2020",
    "effectiveAt": "15 April 2020",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/3/282b5b0967ea931ce9d6be6b895c24e6"
  },
  {
    "id": 277,
    "title": "Infografis Lisensi K3",
    "subtitle": "",
    "image": "",
    "number": "-",
    "type": "Infografis",
    "issuer": "-",
    "sector": "Infografis",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "7 Desember 2020",
    "effectiveAt": "7 Desember 2020",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/29/a21b80030ab8a3b2ee735dfef89e1b44"
  },
  {
    "id": 278,
    "title": "Infografis Keaslian Lisensi K3",
    "subtitle": "",
    "image": "",
    "number": "-",
    "type": "Infografis",
    "issuer": "-",
    "sector": "Infografis",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "7 Desember 2020",
    "effectiveAt": "7 Desember 2020",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/28/53b1468f901b522fd734fcc4b60884c2"
  },
  {
    "id": 279,
    "title": "Infografis Tata Cara Lisensi K3",
    "subtitle": "",
    "image": "",
    "number": "-",
    "type": "Infografis",
    "issuer": "-",
    "sector": "Infografis",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "7 Desember 2020",
    "effectiveAt": "7 Desember 2020",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/27/073293ce5b953a4a281cc118e310d38a"
  },
  {
    "id": 280,
    "title": "Peraturan Menteri Tenaga Kerja No. Per. 02/Men/1983 Tentang Instalasi Alarm Kebakaran Otomatik",
    "subtitle": "",
    "image": "",
    "number": "2",
    "type": "Peraturan Menteri Tenaga Kerja No. Per. 02/Men/1983",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Penanggulangan Kebakaran",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "10 Agustus 1983",
    "effectiveAt": "10 Agustus 1983",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/54/217b49b4e1ad68461d54fa40cae93aee"
  },
  {
    "id": 281,
    "title": "Keputusan Menteri Tenaga Kerja No. Kep. 186/Men/1999 Tentang Unit Penanggulangan Kebakaran di Tempat Kerja",
    "subtitle": "",
    "image": "",
    "number": "186",
    "type": "Keputusan Menteri Tenaga Kerja No. Kep. 186/Men/1999",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Penanggulangan Kebakaran",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "29 September 1999",
    "effectiveAt": "29 September 1999",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/53/4befcf7c2fa0b02558b6259cec67047c"
  },
  {
    "id": 282,
    "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 04/Men/1980 Tentang Syarat-syarat Pemasangan dan Pemeliharaan APAR",
    "subtitle": "",
    "image": "",
    "number": "4",
    "type": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 04/Men/1980",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Penanggulangan Kebakaran",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "14 April 1980",
    "effectiveAt": "14 April 1980",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/52/2b6f3f64664cea53d9527b9388c9e67d"
  },
  {
    "id": 283,
    "title": "Instruksi Menteri Tenaga Kerja No. Ins.11/M/BW/1997 Tentang Pengawasan K3 Khusus Penanggulangan Kebakaran",
    "subtitle": "",
    "image": "",
    "number": "11",
    "type": "Instruksi Menteri Tenaga Kerja No. Ins.11/M/BW/1997 Tentang Pengawasan K3 Khusus",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Penanggulangan Kebakaran",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "27 Oktober 1997",
    "effectiveAt": "27 Oktober 1997",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/50/a10d845e74931047fef95f81ce3cd544"
  },
  {
    "id": 284,
    "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 08/Men/VII/2010 Tentang Alat Pelindung Diri",
    "subtitle": "",
    "image": "",
    "number": "8",
    "type": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 08/Men/VII/2010",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait APD",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "6 Juli 2010",
    "effectiveAt": "6 Juli 2010",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/58/8925f3beb59ad33fb8927dc61b598004"
  },
  {
    "id": 285,
    "title": "INSTRUKSI MENTERI TENAGA KERJA NO. : Ins. 2/M/BW/BK/1984 Tentang Alat Pelindung Diri",
    "subtitle": "",
    "image": "",
    "number": "2",
    "type": "INSTRUKSI MENTERI TENAGA KERJA NO. : Ins. 2/M/BW/BK/1984",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait APD",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "30 Agustus 1984",
    "effectiveAt": "30 Agustus 1984",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/57/a73c4ca866e46a25de47a68063354750"
  },
  {
    "id": 286,
    "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per.02/Men/1982 Tentang Kwalifikasi Juru Las di Tempat Kerja",
    "subtitle": "",
    "image": "",
    "number": "02",
    "type": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per.02/Men/1982",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Pengelasan",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "8 Maret 1982",
    "effectiveAt": "8 Maret 1982",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/69/f4ab25383d246f3ffe982768240c8f30"
  },
  {
    "id": 287,
    "title": "Kepdirjen No. 64 Tahun 2013 tentang Pedoman Pembinaan Keselamatan dan Kesehatan Kerja Pekerjaan Penyelaman di Dalam Air (Underwater Diving Work)",
    "subtitle": "",
    "image": "",
    "number": "64",
    "type": "Kepdirjen",
    "issuer": "-",
    "sector": "Norma,Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Penyelaman",
    "jurisdiction": "Nasional",
    "status": "Berlaku",
    "publishedAt": "1 Oktober 2013",
    "effectiveAt": "1 Oktober 2013",
    "summary": "",
    "keywords": [],
    "sourceUrl": "https://temank3.kemnaker.go.id/page/perundangan_detail/84/29fc0558a0853d1e6a4e1b90c187532a"
  }
]
