export const scrapedRegulationData = [
  {
    "id": "perundangan-k3",
    "name": "Perundangan K3",
    "subCategories": [
      {
        "id": "undang-undang-perpuu-terkait-k3",
        "name": "Undang-Undang/PERPUU terkait K3",
        "regulations": [
          {
            "id": 200,
            "title": "Undang-Undang No 1 Tahun 1970 tentang Keselamatan Kerja",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 201,
            "title": "Undang-Undang Uap Tahun 1930 (Stoom Ordonnantie 1930)(Staatsblad No. 225 Tahun 1930)",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          }
        ]
      },
      {
        "id": "norma-standar-pedoman-kriteria-nspk-k3-terkait-bidang-smk3",
        "name": "Norma, Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang SMK3",
        "regulations": [
          {
            "id": 202,
            "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 01/Men/2007 Tentang Pedoman Pemberian Penghargaan K3",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 203,
            "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per.26/Men/2014 Tentang Penyelenggaraan Penilaian Penerapan SMK3",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 204,
            "title": "Peraturan Pemerintah Nomor 50 Tahun 2012 tentang Penerapan Sistem Manajemen Keselamatan dan Kesehatan Kerja",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          }
        ]
      },
      {
        "id": "norma-standar-pedoman-kriteria-nspk-k3-terkait-bidang-keahlian-dan-kelembagaan-k3",
        "name": "Norma, Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Keahlian dan Kelembagaan K3",
        "regulations": [
          {
            "id": 205,
            "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 04/Men/1987 Tentang Panitia Pembina Keselamatan dan Kesehatan Kerja dan Penunjukan Ahli Kesel",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 206,
            "title": "Peraturan Menteri Tenaga Kerja Nomor Per-02/MEN/1992 tentang Tata Cara Penunjukan, Kewajiban dan Wewenang Ahli Keselamatan dan Kesehatan Kerja",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 207,
            "title": "Peraturan Menteri Tenaga Kerja Nomor Per-04/MEN/1995 tentang Perusahaan Jasa Keselamatan dan Kesehatan Kerja",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          }
        ]
      },
      {
        "id": "norma-standar-pedoman-kriteria-nspk-k3-terkait-bidang-uap",
        "name": "Norma, Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Uap",
        "regulations": [
          {
            "id": 208,
            "title": "PERATURAN MENTERI KETENAGAKERJAAN REPUBLIK INDONESIA NOMOR 4 TAHUN 2025 TENTANG OPERATOR PESAWAT UAP",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 209,
            "title": "Checklist Pemeriksaan Pesawat Uap Bentuk 9A",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 210,
            "title": "Pemeriksaan Pertama Pesawat Uap selain Ketel Uap Bentuk 9",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 211,
            "title": "Pemeriksaan Pertama Ketel Uap Bentuk 10",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 212,
            "title": "Laporan Bulanan Pemeriksaan Pesawat Uap dan Bejana Tekanan Bentuk U-5",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 213,
            "title": "Laporan Pengawasan Pembuatan Pesawat Uap Bentuk 1",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 214,
            "title": "Akte Izin Penggunaan Pesawat Uap Bentuk 6B",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 215,
            "title": "Surat Permohonan Surat Keterangan Kelayakan Pesawat Uap Bentuk 6A",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 216,
            "title": "Surat Permohonan Pengesahan Gambar Rencana Pesawat Uap Bentuk 6",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 217,
            "title": "Surat Permohonan Penggunaan Pesawat Uap",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 218,
            "title": "Peraturan Uap Tahun 1930 (Stoom Verordening)",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 219,
            "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per.01/Men/1988 Tentang Kwalifikasi dan Syarat-Syarat Operator Pesawat Uap",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          }
        ]
      },
      {
        "id": "norma-standar-pedoman-kriteria-nspk-k3-terkait-bidang-bejana-tekanan-dan-tangki-timbun",
        "name": "Norma, Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Bejana Tekanan dan Tangki Timbun",
        "regulations": [
          {
            "id": 220,
            "title": "Peraturan Menteri Tenaga Kerja Nomor Per-01/MEN/1992 tentang Syarat-Syarat Keselamatan dan Kesehatan Kerja Pesawat Karbid",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 221,
            "title": "Peraturan Menteri Ketenagakerjaan RI Nomor 37 Tahun 2016 tentang Keselamatan dan Kesehatan Kerja Bejana Tekanan dan Tangki Timbun",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          }
        ]
      },
      {
        "id": "norma-standar-pedoman-kriteria-nspk-k3-terkait-bidang-pesawat-angkat-dan-pesawat-angkut",
        "name": "Norma, Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Pesawat Angkat dan Pesawat Angkut",
        "regulations": [
          {
            "id": 222,
            "title": "Lampiran Peraturan Menteri Ketenagakerjaan Tentang Keselamatan dan Kesehatan Kerja No. 8 Tahun 2020 Tentang Pesawat Angkat dan Pesawat Angkut",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 223,
            "title": "Peraturan Menteri Ketenagakerjaan No. 8 Tahun 2020 Tentang Keselamatan dan Kesehatan Kerja Pesawat Angkat dan Pesawat Angkut",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          }
        ]
      },
      {
        "id": "norma-standar-pedoman-kriteria-nspk-k3-terkait-bidang-pesawat-tenaga-dan-produksi",
        "name": "Norma, Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Pesawat Tenaga dan Produksi",
        "regulations": [
          {
            "id": 224,
            "title": "Peraturan Menteri Ketenagakerjaan RI Nomor 38 Tahun 2016 tentang Keselamatan dan Kesehatan Kerja Pesawat Tenaga dan Produksi",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          }
        ]
      },
      {
        "id": "norma-standar-pedoman-kriteria-nspk-k3-terkait-bidang-konstruksi-dan-bangunan",
        "name": "Norma, Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Konstruksi dan Bangunan",
        "regulations": [
          {
            "id": 225,
            "title": "Sertifikasi Kompetensi K3 Bidang Konstruksi Bangunan",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 226,
            "title": "Kepdirjen Binwasnaker No. 74/PPK/XII/2013 Tentang Lisensi K3 Bidang Supervisi Perancah",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 227,
            "title": "Keputusan Dirjen PHI dan Wasnaker No. 20/DJPPK/VI/2004 Tentang Sertifikasi Kompetensi K3 Bidang Konstruksi Bangunan",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 228,
            "title": "Surat Edaran No. S. 4 Tahun 1997 Dirjen PHI dan Wasnaker Tentang Wajib Lapor Pekerjaan Proyek Konstruksi Bangunan",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 229,
            "title": "Keputusan Bersama Menteri Tenaga Kerja dan Menteri Pekerjaan Umum No. 174/Men/1986 tentang Keselamatan dan Kesehatan Kerja Pada Tempat Kegiatan Konstr",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 230,
            "title": "Peraturan Menteri Tenaga Kerja No. Per.01/Men/1980 Tentang Keselamatan dan Kesehatan Kerja Pada Konstruksi Bangunan",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          }
        ]
      },
      {
        "id": "norma-standar-pedoman-kriteria-nspk-k3-terkait-bidang-listrik-dan-penyalur-petir",
        "name": "Norma, Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Listrik dan Penyalur Petir",
        "regulations": [
          {
            "id": 231,
            "title": "Kepdirjen Binwasnaker dan K3 No.Kep. 48/PPK&K3/VIII/2015 Tentang Pembinaan Teknii K3 Listrik",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 232,
            "title": "Kepdirjen Binwasnaker dan K3 No.Kep. 47/PPK&K3/VIII/2015 Tentang Pembinaan Calon Ahli K3 Bidang Listrik",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 233,
            "title": "Peraturan Menteri Tenaga Kerja No. Per. 02/Men/1989 Tentang Pengawasan Instalasi Penyalur Petir",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 234,
            "title": "Peraturan Menteri Ketenagakerjaan RI Nomor 12 Tahun 2015 tentang Keselamatan dan Kesehatan Kerja Listrik di Tempat Kerja",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 235,
            "title": "Peraturan Menteri Ketenagakerjaan RI Nomor 33 Tahun 2015 tentang Perubahan Atas Peraturan Menteri Ketenagakerjaan Nomor 12 Tahun 2015 tentang Keselama",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 236,
            "title": "Peraturan Menteri Ketenagakerjaan RI Nomor 31 Tahun 2015 tentang Perubahan Atas Peraturan Menteri Tenaga Kerja Nomor Per.02/MEN/1989 tentang Pengawasa",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          }
        ]
      },
      {
        "id": "norma-standar-pedoman-kriteria-nspk-k3-terkait-bidang-elevator-dan-eskalator",
        "name": "Norma, Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Elevator dan Eskalator",
        "regulations": [
          {
            "id": 237,
            "title": "Peraturan Menteri Ketenagakerjaan RI Nomor 6 Tahun 2017 tentang Keselamatan dan Kesehatan Kerja Elevator dan Eskalator",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          }
        ]
      },
      {
        "id": "norma-standar-pedoman-kriteria-nspk-k3-terkait-bidang-kesehatan-kerja",
        "name": "Norma, Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Kesehatan Kerja",
        "regulations": [
          {
            "id": 238,
            "title": "PEDOMAN PEMBERIAN PENGHARGAAN PROGRAM PENCEGAHAN DAN PENANGGULANGAN HIV DAN AIDS DI TEMPAT KERJA",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 239,
            "title": "Surat Edaran Menteri Tenaga dan Transmigrasi No.SE.01/MEN/1979 Tentang PENGADAAN KANTIN DAN RUANG TEMPAT MAKAN",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 240,
            "title": "Keputusan Menteri Tenaga Kerja dan Transmigrasi No. Kep. 68/Men/IV/2004 Tentang Pencegahan dan Penanggulangan HIV/AIDS di Tempat Kerja",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 241,
            "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 11/Men/VI/2005 Tentang Pencegahan dan Penanggulangan Penyalahgunaan dan Peredaran Narkotika,",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 242,
            "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 01/Men/1981 Tentang Kewajiban Melapor Penyakit Akibat Kerja",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 243,
            "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 15/Men/VIII/2008 Tentang P3K di Tempat Kerja",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 244,
            "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 03/Men/1982 Tentang Pelayanan Kesehatan Tenaga Kerja",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 245,
            "title": "Peraturan Menteri Tenaga Kerja, Transmigrasi, dan Koperasi No. Per. 01/Men/1976 Tentang Kewajiban Latihan Hyperkes Dokter Perusahaan",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 246,
            "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 02/Men/1980 Tentang Pemeriksaan Kesehatan Tenaga Kerja dalam Rangka Penyelenggaraan Keselamat",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 247,
            "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 01/Men/1979 Tentang Kewajiban Latihan Hygiene Perusahaan K3 Bagi Tenaga Medis Perusahaan",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 248,
            "title": "PEDOMAN PEMBERIAN PENGHARGAAN PROGRAM PENCEGAHAN DAN PENANGGULANGAN COVID-19 DI TEMPAT KERJA",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 249,
            "title": "ANTISIPASI MENINGKATNYA KASUS KONFIRMASI COVID 19 DI TEMPAT KERJA",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 250,
            "title": "Senam Pekerja Sehat",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 251,
            "title": "Pedoman Penyusunan Keberlangsungan Usaha Dalam Masa Pandemi Penyakit",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 252,
            "title": "Kewaspadaan Penyebaran Penyakit Pneumonia Berat yang Tidak Diketahui Penyebabnya pada Pekerja",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 253,
            "title": "Kesiapsiagaan dalam Menghadapi Penyebaran Covid-19 di Tempat Kerja",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 254,
            "title": "Perlindungan Pekerja/Buruh dalam Program Jaminan Kecelakaan Kerja pada Kasus Penyakit Akibat Kerja karena Corona Virus Disease (COVID-19)",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 255,
            "title": "Perlindungan Pekerja/Buruh dan Kelansungan Usaha dalam Rangka Pencegahan dan Penanggulangan COVID-19",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 256,
            "title": "Protokol Keselamatan Dan Kesehatan Kerja (K3) Kembali Bekerja Dalam Pencegahan Penularan Covid-19",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 257,
            "title": "Pedoman Penyusunan Perencanaan Keberlangsungan Usaha Dalam Menghadpi Pandemi Corona Virus Disease 2019 (Covid-19) Bagi Usaha Kecil Dan Menengah (UKM)",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 258,
            "title": "Surat Edaran Direktur Jenderal Binwasnaker dan K3 Nomor 5/1923/AS.02.03/VI/2020 tentang Pembinaan K3 dalam masa Pandemi Covid-19",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 259,
            "title": "Keputusan Direktur Jenderal Pembinaan Pengawasan Ketenagakerjaan dan Keselamatan dan Kesehatan Kerja Nomor 5/36/HM.01/IV/2020 tentang Pedoman Penyusun",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 260,
            "title": "Surat Edaran Menteri Ketenagakerjaan RI Nomor M/7/AS.02.02/V/2020 tentang Rencana Keberlangsungan Usaha dalam Menghadapi Pandemi Corona Virus Disease",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          }
        ]
      },
      {
        "id": "norma-standar-pedoman-kriteria-nspk-k3-terkait-bidang-ergonomi-dan-lingkungan-kerja",
        "name": "Norma, Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Ergonomi dan Lingkungan Kerja",
        "regulations": [
          {
            "id": 261,
            "title": "Surat Edaran Menteri Tenaga dan Transmigrasi No.SE.01/MEN/PPK/IV/2012Tentang Kewajiban Syarat-Syarat Keselamatan dan Kesehatan Kerja di Ruang Terbatas",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 262,
            "title": "Peraturan Menteri Ketenagakerjaan No. 9 Tahun 2016 Tentang Keselamatan dan Kesehatan Kerja Pada Ketinggian",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 263,
            "title": "Peraturan Menteri Ketenagakerjaan RI Nomor 5 Tahun 2018 tentang Keselamatan dan Kesehatan Kerja Lingkungan Kerja",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          }
        ]
      },
      {
        "id": "norma-standar-pedoman-kriteria-nspk-k3-terkait-bidang-bahan-berbahaya",
        "name": "Norma, Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Bahan Berbahaya",
        "regulations": [
          {
            "id": 264,
            "title": "Keputusan Menteri Tenaga Kerja No. Kep.187/Men/1999 Tentang Pengendalian Bahan Berbahaya di Tempat Kerja",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          }
        ]
      },
      {
        "id": "user-guide",
        "name": "User Guide",
        "regulations": [
          {
            "id": 265,
            "title": "Tata Cara Pembinaan Personel K3 di PJK3 dan PNBP V.3.2.",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 266,
            "title": "Tata Cara Pengajuan SKP PJK3 V.3.0",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 267,
            "title": "Tata Cara Pendaftaran SKP Dokter Perusahaan",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 268,
            "title": "Tata Cara PENDAFTARAN SKP AHLI - AUDITOR INTERNAL",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 269,
            "title": "Tata Cara Perpanjangan Personel V 2.1",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 270,
            "title": "Tata Cara Teman K3 bagi PJK3 ver 2.1",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          }
        ]
      },
      {
        "id": "surat-edaran",
        "name": "Surat Edaran",
        "regulations": [
          {
            "id": 271,
            "title": "Surat Edaran Direktur BKK3 Nomor 5/244/AS.02/VIII/2021 tentang Pelaksanaan Pembinaan K3 Wilayah yang Menerapkan PPKM Level 4, Level 3, Level 2",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 272,
            "title": "Optimalisasi Penerapan Protokol Kesehatan di Tempat Kerja dan Penyedian Perlengkapan Serta Sarana Kesehatan Bagi Pekerja/Buruh Oleh Perusahaan Selama",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 273,
            "title": "Surat Edaran Direktur BKK3 Nomor 5/181/AS.02.00/VII/2021 tentang Pelaksanaan Pembinaan K3 Wilayah yang Menerapkan PPKM Darurat",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 274,
            "title": "Surat Edaran Direktur BKK3 Nomor 5/170/AS.02.00/VII/2021 tentang Pembinaan K3 pada Masa PPKM Darurat Jawa Bali Juli 2021",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 275,
            "title": "Surat Edaran Direktur Pengawasan Norma K3 Nomor 5/2419/AS.02.00/VIII/2020 tentang Pelaksanaan Pembinaan K3",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 276,
            "title": "Surat Edaran Direktur Pengawasan Norma K3 Nomor 5/1007/AS.02/IV/2020 tentang Pembinaan K3 Berbasis Dalam Jaringan (Online)",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          }
        ]
      },
      {
        "id": "infografis",
        "name": "Infografis",
        "regulations": [
          {
            "id": 277,
            "title": "Infografis Lisensi K3",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 278,
            "title": "Infografis Keaslian Lisensi K3",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 279,
            "title": "Infografis Tata Cara Lisensi K3",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          }
        ]
      },
      {
        "id": "norma-standar-pedoman-kriteria-nspk-k3-terkait-bidang-penanggulangan-kebakaran",
        "name": "Norma, Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Penanggulangan Kebakaran",
        "regulations": [
          {
            "id": 280,
            "title": "Peraturan Menteri Tenaga Kerja No. Per. 02/Men/1983 Tentang Instalasi Alarm Kebakaran Otomatik",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 281,
            "title": "Keputusan Menteri Tenaga Kerja No. Kep. 186/Men/1999 Tentang Unit Penanggulangan Kebakaran di Tempat Kerja",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 282,
            "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 04/Men/1980 Tentang Syarat-syarat Pemasangan dan Pemeliharaan APAR",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 283,
            "title": "Instruksi Menteri Tenaga Kerja No. Ins.11/M/BW/1997 Tentang Pengawasan K3 Khusus Penanggulangan Kebakaran",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          }
        ]
      },
      {
        "id": "norma-standar-pedoman-kriteria-nspk-k3-terkait-apd",
        "name": "Norma, Standar, Pedoman, Kriteria (NSPK) K3 terkait APD",
        "regulations": [
          {
            "id": 284,
            "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per. 08/Men/VII/2010 Tentang Alat Pelindung Diri",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          },
          {
            "id": 285,
            "title": "INSTRUKSI MENTERI TENAGA KERJA NO. : Ins. 2/M/BW/BK/1984 Tentang Alat Pelindung Diri",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          }
        ]
      },
      {
        "id": "norma-standar-pedoman-kriteria-nspk-k3-terkait-bidang-pengelasan",
        "name": "Norma, Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Pengelasan",
        "regulations": [
          {
            "id": 286,
            "title": "Peraturan Menteri Tenaga Kerja dan Transmigrasi No. Per.02/Men/1982 Tentang Kwalifikasi Juru Las di Tempat Kerja",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          }
        ]
      },
      {
        "id": "skkni-sni",
        "name": "SKKNI / SNI",
        "regulations": []
      },
      {
        "id": "norma-standar-pedoman-kriteria-nspk-k3-terkait-bidang-penyelaman",
        "name": "Norma, Standar, Pedoman, Kriteria (NSPK) K3 terkait bidang Penyelaman",
        "regulations": [
          {
            "id": 287,
            "title": "Kepdirjen No. 64 Tahun 2013 tentang Pedoman Pembinaan Keselamatan dan Kesehatan Kerja Pekerjaan Penyelaman di Dalam Air (Underwater Diving Work)",
            "subtitle": "",
            "image": "",
            "number": "",
            "type": "",
            "issuer": "",
            "sector": "",
            "jurisdiction": "Nasional",
            "status": "Berlaku",
            "publishedAt": "",
            "effectiveAt": "",
            "summary": "",
            "keywords": [],
            "sourceUrl": "#"
          }
        ]
      },
      {
        "id": "pedoman-keselamatan-dan-keselamatan-k3-apd-terkait-bidang-konstruksi-dan-bangunan",
        "name": "Pedoman Keselamatan dan Keselamatan K3 (APD)terkait bidang Konstruksi dan Bangunan",
        "regulations": []
      },
      {
        "id": "norma-standar-pedoman-kriteria-nspk-k3-terkait-bidang-perusahaan-jasa-k3",
        "name": "Norma, Standar, Pedoman, Kriteria (NSPK) K3 terkait Bidang Perusahaan Jasa K3",
        "regulations": []
      }
    ]
  }
];
